### ISSUE TITLE
report is overriden for same url , summary contains proper information

### ISSUE THREAD

**Issue by tyge68** [femtopixel/google-lighthouse-puppeteer#4]
If you use multiple time the same url (to basically get min, max, percentile) for loading same url,
unfortunately the reports are overridden, so only the last report is available, in the summary.json the data show the multiple urls, but since all points to same file it is useless.

Can it be fixed so each requested url reports are stored in unique files ?

**Comment by tyge68** [comment]
most likely the issue is in lighthouse-batch, the method 
function siteName(site) {
  return site.replace(/^https?:\/\//, '').replace(/[\/\?#:\*\$@\!\.]/g, '_')
}
is wrong, it shouldn't replace only in the url as the url might be super long etc.. best would be to "shorter" it and add some uuid to make it unique per run url. I couldn't find the lighthouse-batch git repo

**Comment by tyge68** [comment]
Actually I filed an issue here https://github.com/mikestead/lighthouse-batch/issues/32

**Comment by tyge68** [comment]
Once fixed then only need to update to use latest lighthouse-batch I guess and release a new docker image

**Comment by jaymoulin** [comment]
Thank you for reporting this.

If you find this library or its docker image useful, please consider donation (Github's Sponsor button and README top badges).

I have several points of attention to notice:
- As you clearly highlighted, the generated output filename is in the `lighthouse-batch` dependency in a private method (I cannot override it).
- Altering the output generated filename may result in a BC break and might be a meaningful reason for the original maintainer to not accept this PR.
- The dependency had the latest release in June (6 month+) and might be an unmaintained library or very long to be accepted.
- Your PR suggest adding the queue number to the generated filename for the `report.json` file ONLY and probably should be available for HTML reports as well. This very PR deprecates the `siteName` method for the `report.json` in the actual state, and completely deprecated with my suggestion. I'm pretty sure the README should be updated as well.
- I'll do compatibility fixes on this repository if needed in case of BC Break.
- [The docker image](https://github.com/femtopixel/docker-google-lighthouse-puppeteer) will automatically be updated in case one of the following dependency unleash a new release : ([Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) or [Google Puppeteer](https://github.com/puppeteer/puppeteer) or [Femtopixel/google-lighthouse-puppeteer npm package](https://github.com/femtopixel/google-lighthouse-puppeteer)).

For I understand this kind of problematic, If you really need your suggested feature to be available as soon as possible, I suggest you fork all of the following repositories: 
- https://github.com/mikestead/lighthouse-batch to include your PR.
- https://github.com/femtopixel/google-lighthouse-puppeteer to use your new `lighthouse-batch` package.
- https://github.com/femtopixel/docker-google-lighthouse-puppeteer to use your new `lighthouse-puppeteer` package in a new Docker image.

**Comment by tyge68** [comment]
I fixed it locally so in my case it works, and automating to "patch" the docker as workaround is enough for my use case.

If anyone else has the issue in future eventually it would make sense it get fixed permanently in lighthouse-batch indeed.
