### ISSUE TITLE
How to I run lighthouse puppeteer in non-headless way

### ISSUE THREAD

**Issue by scssyworks** [femtopixel/google-lighthouse-puppeteer#5]
**Description**
Lighthouse puppeteer runs chrome in headless mode. I want to disable headless flag to basically see what's happening on the page.

**Version of google-lighthouse-puppeteer (yarn list global google-lighthouse-puppeteer) or (npm list global google-lighthouse-puppeteer)**
Latest version

**Command line I used**
I did not use command line. I have written a node script as per documentation which runs the test script.

**Steps to reproduce the issue:**
I am not reporting an issue. I just want to know if there is a way to run chrome in no headless manner.

**Describe the results you received:**
Need a way to disable headless mode that's all.

**Describe the results you expected:**
Need a way to disable headless mode that's all.

**Additional information you deem important (e.g. issue happens only occasionally):**
No additional information. I think my problem statement is quite clear

**Provide some logs**

<details>
<pre>
no logs
</pre>
</details>

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).
